name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨执行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream repo
        run: git remote add upstream https://github.com/pppscn/SmsForwarder.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Get current user info
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/users/${{ github.actor }})
          echo "Current user info: $response"

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin main    
