name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 1' # 每周一凌晨执行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repo
        run: git remote add upstream https://github.com/pppscn/SmsForwarder.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main || (git merge --abort && exit 1)

      - name: Push changes
        run: git push origin main
